.PHONY: clean All

All:
	@echo "----------Building project:[ INF442 - Debug ]----------"
	@"$(MAKE)" -f  "INF442.mk"
clean:
	@echo "----------Cleaning project:[ INF442 - Debug ]----------"
	@"$(MAKE)" -f  "INF442.mk" clean
